name: Greet on Master Push

on:
  push:
    branches:
      - master

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Greet
      run: |
        echo "Hello, World! This workflow runs on the master branch."
