name: Merge Changes to Another Repository

on:
  push:
    branches:
      - main # Change this to the branch you want to monitor for changes

jobs:
  merge_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        repository: ambikesh-cedcommerce/mygitactions # Change to the source repository's owner and name
        ref: ${{ github.ref }}

    - name: Merge changes into target repository
      run: |
        git remote add target-repo https://github.com/ambikesh-cedcommerce/mygitactions.git # Change to the target repository's owner and name
        git fetch target-repo
        git checkout -b target-branch target-repo/target-branch
        git merge origin/${{ github.ref }}
        git push target-repo target-branch
      env:
        GITHUB_TOKEN: ${{ secrets.MYGITHUBSECRETE }} # Personal Access Token with repository access
