name: Merge Branch to Another Repository

on:
  push:
    branches:
      - main  # Change this to your source branch name

env:
  GH_TOKEN: ${{ secrets.MYGITHUBSECRETE }}

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "${{ secrets.GITHUB_ACTOR }}"
        git config user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
        git remote add target-repo https://github.com/ambikesh-cedcommerce/mygitactions.git

    - name: Install GitHub CLI (gh)
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: Authenticate with Personal Access Token
      run: |
        unset GH_TOKEN
        echo $GH_TOKEN | gh auth login --with-token

    - name: Fetch Target Repository Branch
      run: git fetch target-repo main:main  # Replace 'main' with the source branch name

    - name: Merge Branch
      run: |
        git checkout main  # Replace 'main' with the source branch name
        git merge main  # Replace 'main' with the source branch name
        git push origin main  # Replace 'main' with the source branch name
